### ISSUE TITLE
`Hbc::DSL#license` is deprecated

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [robertgzr/homebrew-tap#3]
Having this tapped prevents me from using Homebrew, period, right now:

```
Error: Calling Hbc::DSL#license is disabled! There is no replacement.
Please report this to the robertgzr/tap tap:
  /usr/local/Homebrew/Library/Taps/robertgzr/homebrew-tap/Casks/font-noto-mono.rb:8
```

**Comment by BW2010** [comment]
same:
`Error: Calling Hbc::DSL#license is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/robertgzr/homebrew-tap/Casks/font-iosevka-inziu.rb:8:in block in load
Please report this to the robertgzr/tap tap!`

**Comment by robertgzr** [comment]
might be a bit late but I removed the cask since it's in the official repo 
https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-noto-mono.rb
